// level: words

export default {
    1: [
        'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
        'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
        'u', 'v', 'w', 'x', 'y', 'z'
    ],
    2: [
        'à', 'au', 'ça', 'ce', 'ci', 'de', 'du', 'en', 'et', 'il', 'je', 'la',
        'le', 'ma', 'me', 'ne', 'on', 'ou', 'sa', 'se', 'si', 'ta', 'te', 'tu',
        'un', 'va', 've', 'ami', 'ans', 'bas', 'bon', 'bus', 'car', 'cas', 'ces',
        'cou', 'des', 'dit', 'don', 'dos', 'eau', 'est', 'eux', 'fais', 'fin',
        'foi', 'gros', 'haut', 'ici', 'ile', 'ils', 'jeu', 'jour', 'les', 'lieu',
        'lit', 'main', 'mer', 'mes', 'mot', 'mur', 'net', 'nos', 'nul', 'oeil',
        'or', 'pas', 'peu', 'pied', 'plat', 'plus', 'pour', 'près', 'quand',
        'qui', 'rue', 'sans', 'ses', 'soit', 'sol', 'son', 'sous', 'sur', 'tes',
        'toi', 'ton', 'trop', 'très', 'vie', 'vin', 'voir', 'vous'
    ],
    3: [
        'abri', 'acte', 'agir', 'aime', 'airs', 'aller', 'alors', 'amis', 'amour',
        'annee', 'arme', 'arts', 'aussi', 'autre', 'avant', 'avec', 'avis', 'beau',
        'bien', 'bleu', 'bois', 'bref', 'bruit', 'camp', 'casa', 'cause', 'cette',
        'chez', 'choix', 'chose', 'ciel', 'cité', 'clair', 'coeur', 'comme',
        'corps', 'côté', 'coup', 'cours', 'crois', 'dame', 'dans', 'début', 'deux',
        'dieu', 'dire', 'droit', 'éclat', 'effet', 'elles', 'enfin', 'entre',
        'envie', 'esprit', 'essai', 'etat', 'être', 'face', 'fait', 'femme', 'feu',
        'fils', 'fleur', 'foi', 'fois', 'force', 'forme', 'fort', 'frais', 'frère',
        'gens', 'grand', 'gros', 'groupe', 'haut', 'heure', 'histoire', 'idée',
        'image', 'jambe', 'jeune', 'jeux', 'joli', 'jour', 'juste', 'là', 'leur',
        'lieu', 'livre', 'loin', 'lois', 'lune', 'main', 'mais', 'mal', 'manque'
    ],
    4: [
        'abord', 'agent', 'aimer', 'aller', 'alors', 'amour', 'année', 'appel',
        'arbre', 'argent', 'assez', 'autre', 'avant', 'avoir', 'beau', 'beauté',
        'besoin', 'bient', 'bleue', 'boire', 'bruit', 'cadre', 'calme', 'carte',
        'cause', 'célèbre', 'cercle', 'chair', 'chambre', 'champ', 'chance',
        'chanter', 'chaque', 'chemin', 'cher', 'cheval', 'chien', 'choix', 'chose',
        'clair', 'classe', 'coeur', 'comble', 'comme', 'compte', 'corps', 'côté',
        'couleur', 'courir', 'cours', 'couvre', 'créer', 'crise', 'croire',
        'dame', 'danger', 'début', 'dedans', 'dehors', 'demi', 'dernier', 'désir',
        'devoir', 'dieu', 'dire', 'doigt', 'doute', 'droit', 'école', 'écrire',
        'effet', 'église', 'élève', 'enfant', 'enfin', 'entrer', 'espace', 'esprit',
        'essai', 'état', 'étoile', 'être', 'exact', 'facon', 'faire', 'famille',
        'femme', 'fenêtre', 'fête', 'feuille', 'fleur', 'force', 'forme', 'frais',
        'france', 'frère', 'garde'
    ],
    5: [
        'abords', 'action', 'actuel', 'affaire', 'aider', 'aimable', 'allez',
        'amener', 'amitié', 'amour', 'ancien', 'anglais', 'animal', 'années',
        'appeler', 'apprendre', 'argent', 'article', 'artiste', 'aucune', 'aujourd',
        'auteur', 'autres', 'avance', 'avantage', 'avenir', 'avis', 'basé',
        'battre', 'beauté', 'besoin', 'bizarre', 'blanche', 'bleue', 'bonheur',
        'bourse', 'branche', 'brillant', 'bruit', 'cadre', 'calmer', 'candidat',
        'capable', 'caractère', 'causer', 'célèbre', 'centaine', 'central', 'centre',
        'cercle', 'certain', 'chambre', 'chance', 'changement', 'chanter', 'chapitre',
        'chaque', 'charge', 'chemin', 'cheval', 'chiens', 'chiffre', 'choisir',
        'choses', 'cinéma', 'circuit', 'citoyen', 'classe', 'client', 'coeur',
        'collège', 'comment', 'commune', 'compter', 'concept', 'conduire', 'confiance',
        'connu', 'conseil', 'contact', 'contrat', 'contre', 'coucher', 'couleur',
        'courant', 'cuisine', 'culture', 'danser', 'décider', 'défaut', 'demain',
        'demande', 'dernier', 'dessin', 'devoir', 'dieu', 'difficile', 'direct',
        'docteur', 'droite', 'éclater', 'écrire', 'écrivain', 'éducation'
    ],
    6: [
        'absence', 'accepte', 'accident', 'accorder', 'acheter', 'acteurs',
        'actrice', 'adresse', 'affaires', 'agence', 'agir', 'aider', 'allemand',
        'améliorer', 'amour', 'analyse', 'animaux', 'anniversaire', 'annonce',
        'apparaît', 'apporter', 'apprendre', 'argent', 'arrivée', 'article',
        'artisan', 'assemblée', 'asseoir', 'attacher', 'attendre', 'attitude',
        'aucune', 'augmenter', 'auteur', 'avancer', 'avantage', 'avenue', 'avis',
        'bataille', 'bâtiment', 'beauté', 'besoin', 'billets', 'blanche',
        'bonheur', 'bouteille', 'branche', 'brillant', 'cadeau', 'calcule',
        'campagne', 'candidat', 'capable', 'capitale', 'carrière', 'causer',
        'célèbre', 'central', 'centres', 'cérémonie', 'certaine', 'chaleur',
        'chambre', 'changement', 'chanter', 'chapitre', 'charme', 'chemin',
        'chercher', 'cheveux', 'chiffre', 'choisir', 'cinéma', 'circuler',
        'citoyen', 'clair', 'client', 'collège', 'combattre', 'commander',
        'comment', 'commun', 'compétence', 'complet', 'composer', 'comprendre',
        'compter', 'concerne', 'conclure', 'condition', 'confiance', 'connaissance',
        'conseil', 'constante', 'construire', 'contact', 'continuer', 'contrat',
        'contrôle', 'coucher', 'couleur', 'courage', 'courant', 'création'
    ],
    7: [
        'absolument', 'académie', 'accident', 'accepter', 'accomplir', 'accorder',
        'acheter', 'action', 'actrice', 'actuel', 'actuelle', 'adapter', 'addition',
        'admirer', 'adopter', 'adresse', 'affaire', 'affecter', 'agence', 'agir',
        'agricole', 'aider', 'allemand', 'améliorer', 'amitié', 'analyse', 'animaux',
        'anniversaire', 'annonce', 'annuelle', 'apparaît', 'apparence', 'apporter',
        'apprendre', 'approche', 'argent', 'arrivée', 'article', 'artisan',
        'artistique', 'assemblée', 'asseoir', 'assister', 'assurance', 'attacher',
        'atteindre', 'attendre', 'attitude', 'attraction', 'audience', 'augmenter',
        'auteur', 'automatique', 'avancer', 'avantage', 'aviation', 'bataille',
        'bâtiment', 'beauté', 'bénéfice', 'besoin', 'billets', 'blessure',
        'bonheur', 'bouteille', 'branche', 'brillant', 'cadeau', 'calcule',
        'campagne', 'candidat', 'capacité', 'capitale', 'caractère', 'carrière',
        'causer', 'célèbre', 'cérémonie', 'certaine', 'chaleur', 'chambre',
        'changement', 'chanter', 'chapitre', 'charisme', 'chemin', 'chercher',
        'cheveux', 'chiffre', 'cinéma', 'circuler', 'citoyen', 'civilisation',
        'client', 'collège', 'combattre', 'commander', 'commence', 'comment',
        'communauté', 'compagnie', 'compétence', 'complet', 'composer', 'comprendre'
    ],
    default: [
        'absolument', 'accompagnement', 'accomplissement', 'administration',
        'agriculture', 'anniversaire', 'apprentissage', 'architecture',
        'arrondissement', 'assemblée', 'assistance', 'association', 'assurance',
        'attribution', 'automatique', 'autorisation', 'bénéficiaire', 'caractéristique',
        'civilisation', 'collaboration', 'collection', 'commandement', 'commémoration',
        'communication', 'communauté', 'compagnie', 'compréhension', 'comptabilité',
        'concentration', 'conditionnement', 'configuration', 'confirmation',
        'conscience', 'conseiller', 'conséquence', 'conservation', 'considération',
        'construction', 'consultation', 'continuité', 'contribution', 'contrôleur',
        'coordination', 'correspondance', 'déclaration', 'découverte', 'définition',
        'déplacement', 'développement', 'différence', 'direction', 'disposition',
        'documentation', 'éducation', 'élaboration', 'électricité', 'évaluation',
        'expérience', 'explication', 'exploration', 'expression', 'fabrication',
        'formation', 'gouvernement', 'habitation', 'historique', 'imagination',
        'information', 'inscription', 'institution', 'instruction', 'intégration',
        'interaction', 'international', 'introduction', 'investissement', 'journalisme',
        'législation', 'libération', 'manifestation', 'modification', 'navigation',
        'observation', 'opportunité', 'organisation', 'orientation', 'participation',
        'performance', 'population', 'préparation', 'présentation', 'présidence',
        'production', 'profession', 'programmation', 'protection', 'publication',
        'réalisation', 'recherche', 'reconnaissance', 'récupération', 'réglementation',
        'représentation', 'responsabilité', 'restauration', 'sécurité', 'situation',
        'solution', 'soutien', 'structure', 'technologie', 'transformation',
        'utilisation'
    ]
};
